/* Attachment types the reader has to cope with, and the guardrail for each.
   This is the working list for building out the eval suite. */
(function (root) {
'use strict';
root.GUARDRAILS = [
{ type: 'Inline text in the email body', v1: 'handled',
  read: 'Tiers, minimum order, lead time and answers written as prose or a loose list.',
  guard: 'Split the reply history off first, so our own earlier RFQ text is never read as the supplier\'s answer.',
  evalCase: 's01 clean quote, s05 reply thread with our RFQ quoted underneath.' },
{ type: 'Typed PDF quotation with a table', v1: 'handled via transcript',
  read: 'Column headers, one row per quantity break, footer terms.',
  guard: 'When the body and the document disagree, record both and stop for a person. Never silently prefer one.',
  evalCase: 's02 body says 2.45, PDF says 2.65.' },
{ type: 'Scanned image-only PDF', v1: 'needs OCR, always to a person',
  read: 'Nothing without OCR. Text layer is absent.',
  guard: 'Detect the empty text layer and route to manual entry rather than returning an empty quote.',
  evalCase: 'To add: a PDF whose transcript is only [NO TEXT LAYER].' },
{ type: 'Excel workbook, several sheets', v1: 'handled via transcript',
  read: 'The quote sheet among others; merged cells and a header block above the table.',
  guard: 'Name the sheet and cell in the evidence so a person can find the number again.',
  evalCase: 's06 single-sheet price list.' },
{ type: 'CSV price list', v1: 'handled via transcript',
  read: 'One row per product, our item among several.',
  guard: 'Split into one quote per line item and park anything that matches no open enquiry.',
  evalCase: 's07 three products in one file.' },
{ type: 'Photo of a printed rate card', v1: 'handled via transcript',
  read: 'Angled shot, glare, part of the sheet outside the frame.',
  guard: 'Keep the [CUT OFF] and [?] markers. Any value next to one drops below 0.6 confidence and opens a question.',
  evalCase: 's03 right column missing, one digit unreadable.' },
{ type: 'Handwritten quote on paper', v1: 'always to a person',
  read: 'Digits that OCR confuses: 1/7, 0/6, decimal points.',
  guard: 'Never accept a handwritten price without confirmation, whatever the confidence looks like.',
  evalCase: 'To add: handwritten card with an ambiguous decimal.' },
{ type: 'WeChat or WhatsApp screenshot', v1: 'handled via transcript',
  read: 'Interleaved messages from both sides, prices revised mid-conversation.',
  guard: 'Only the supplier\'s own lines count as evidence. An unclear speaker caps confidence at 0.5.',
  evalCase: 's08 two speakers, a later message corrects an earlier one.' },
{ type: 'Product photos with prices overlaid', v1: 'to a person',
  read: 'Price stickers or captions burned into a product image.',
  guard: 'Treat as a photo transcript. Do not pair a price with a product unless the layout makes the pairing certain.',
  evalCase: 'To add: three products, three prices, ambiguous pairing.' },
{ type: 'Alibaba, 1688 or Drive links', v1: 'always to a person',
  read: 'Nothing. The page cannot be opened from here.',
  guard: 'Record the link, mark the price as external only, and never treat the quote as comparable.',
  evalCase: 's10 prices only on a shop page.' },
{ type: 'ZIP or RAR archive', v1: 'always to a person',
  read: 'Nothing until unpacked.',
  guard: 'List the archive and ask for the contents. Do not guess from the filename.',
  evalCase: 'To add: quote.zip with no body text.' },
{ type: 'Forwarded or replied thread', v1: 'handled',
  read: 'Several rounds, our RFQ at the bottom, sometimes a code only in the history.',
  guard: 'A code found only in the quoted history matches at reduced confidence and is confirmed by the product.',
  evalCase: 's05 thread; to add: a forward where only the history has the code.' },
{ type: 'Chinese or mixed-language email', v1: 'handled',
  read: 'Terms of trade in Chinese, numbers in either script.',
  guard: 'Evidence stays in the original script with an English gloss beside it, so a reviewer can check the source.',
  evalCase: 's04 Chinese-only quote with EXW terms and a conditional logo offer.' },
{ type: 'Proforma invoice sent instead of a quote', v1: 'to a person',
  read: 'Looks like a quote but commits to quantities and bank details.',
  guard: 'Classify separately. A proforma is not an offer to compare, and bank details must never be auto-extracted.',
  evalCase: 'To add: a proforma with a bank account block.' },
{ type: 'Certificate copies attached', v1: 'partly handled',
  read: 'Certificate name, number, issuing body, scope and expiry.',
  guard: 'A certificate claimed in text without a number or document stays unverified and blocks award, not comparison.',
  evalCase: 's02 FDA on request only, s07 CE with no number.' },
{ type: 'Full catalogue, dozens of SKUs', v1: 'to a person',
  read: 'One of fifty products may be ours, or none.',
  guard: 'Return the best guess with its confidence and the alternatives, never a silent pick.',
  evalCase: 'To add: a 50-line catalogue with two plausible matches.' }
];
})(typeof window !== 'undefined' ? window : globalThis);
